### ISSUE TITLE
Don't scroll item "Add" and "Craft Tasks" actions.

### ISSUE THREAD

**Issue by garlond** [nvll/xivtools#14]
When setting up a long list of items to craft, it would be nice to not have to scroll back to the top to add another item.

"Add" button at the top:
![top](https://user-images.githubusercontent.com/50246290/62432631-9ed47300-b6e5-11e9-9bc1-df0c290c015d.png)

Add and Craft Now missing when scrolling in the middle of a long list:
![mid](https://user-images.githubusercontent.com/50246290/62432659-d2170200-b6e5-11e9-9dc8-1b5c8adf34b7.png)

Craft now at the end:
![bot](https://user-images.githubusercontent.com/50246290/62432664-d93e1000-b6e5-11e9-8b24-39a68570b495.png)

**Comment by nvll** [comment]
Added in 6354967611e00bb893b73c60da2a2d166a1cec20
