### ISSUE TITLE
imgui-0.1.0 renders UI smaller

### ISSUE THREAD

**Issue by garlond** [nvll/xivtools#18]
Both claim DPI factor of 1.

Pre 0.1.0:
![pre-0 1](https://user-images.githubusercontent.com/50246290/62593212-c44eb180-b88a-11e9-8389-b9499d95be2e.PNG)

Post 0.1.0:
![post-0 1](https://user-images.githubusercontent.com/50246290/62593223-c9abfc00-b88a-11e9-9bff-e15514a891fc.PNG)

**Comment by nvll** [comment]
Please only file issues based on master, dev is my sandbox/wip.
