### ISSUE TITLE
Feature: Saved Craft Lists

### ISSUE THREAD

**Issue by mmaine** [nvll/xivtools#21]
A feature to allow pre-saved crafting lists (ie. Teamcraft lists) would allow users to save sets of often crafted items for later use. Potentially useful for creating sets for example for spiritbonding without the need to manually re-add every item and choose which macro is to be used. If items have to be created from raw materials, this would save even more time when creating these listings for Talan.

Here's an extremely poor attempt to draft the idea:
https://i.imgur.com/hX9nGDz.png

**Comment by nvll** [comment]
Importing teamcraft lists via the clipboard (so you can click copy on teamcraft then import in talan) should be merged now.

**Comment by nvll** [comment]
Closing since list importing via the clipboard is functional now. Feel free to re-open if that's not workable.
