### ISSUE TITLE
Itemsearch with multiple items of the same name fails to pick the correct craft

### ISSUE THREAD

**Issue by mmaine** [nvll/xivtools#22]
Items that come up with multiple items with one search do not seem to work.

The leatherworking item "Swallowskin Shoes" is a example, when it attempts to Craft the first one in the list. The GUI has no way to distinguish which of the list to use like the CLI had the option for.

**Comment by nvll** [comment]
Duplicate of #17

**Comment by nvll** [comment]
Duplicate #16
