### ISSUE TITLE
Multiple Durability Options

### ISSUE THREAD

**Issue by mmaine** [nvll/xivtools#33]
Suggesting the addition of multiple options in durability field.

Instead of:

>[[xiv_macro]]
name = "1-50 HQ 1"
durability = 80
min_rlvl = 1
max_rlvl = 50
actions = """
/ac "Trained Eye" <wait.3>
/ac "Careful Synthesis" <wait.3>
"""
[[xiv_macro]]
name = "1-50 HQ 2"
durability = 70
min_rlvl = 1
max_rlvl = 50
actions = """
/ac "Trained Eye" <wait.3>
/ac "Careful Synthesis" <wait.3>
"""
[[xiv_macro]]
name = "1-50 HQ 3"
durability = 40
min_rlvl = 1
max_rlvl = 50
actions = """
/ac "Trained Eye" <wait.3>
/ac "Careful Synthesis" <wait.3>
"""
[[xiv_macro]]
name = "1-50 HQ 4"
durability = 35
min_rlvl = 1
max_rlvl = 50
actions = """
/ac "Trained Eye" <wait.3>
/ac "Careful Synthesis" <wait.3>
"""

it could be compacted to:
>[[xiv_macro]]
name = "1-50 HQ 1"
durability = 35;40;70;80
min_rlvl = 1
max_rlvl = 50
actions = """
/ac "Trained Eye" <wait.3>
/ac "Careful Synthesis" <wait.3>
"""`

or something similar.

**Comment by nvll** [comment]
Done in 0.4.1. durability now takes an array that's common separated for durabilities

Eg
durability = [ 35, 40 ]
