### ISSUE TITLE
ventures.exe doesn't launch

### ISSUE THREAD

**Issue by hatchetjog** [nvll/xivtools#39]
Whenever I try and open ventures.exe nothing happens. Sometimes I'll manage to see a command prompt pop up for a quick flash, less than a second.

talan.exe opens up fine

**Comment by nvll** [comment]
Run it from a command prompt and please paste the error.

**Comment by nvll** [comment]
In case it wasn't clear, ventures has no ui presently. It must be wrong
from cmd.exe or powershell.

**Comment by hatchetjog** [comment]
> In case it wasn't clear, ventures has no ui presently. It must be wrong from cmd.exe or powershell. On Sun, Sep 6, 2020, 10:44 AM Christopher Anderson <chris@nullcode.org> wrote:

Oh okay, I got it working now. Sorry for my ignorance and thank you for helping.

**Comment by nvll** [comment]
No worries, the documentation is very out of date and could also be more clear on this point.
