### ISSUE TITLE
Ventures appears to bug itself out after a few hours, and starts inconsistently

### ISSUE THREAD

**Issue by zbee** [nvll/xivtools#41]
When left running overnight I came back to a couple of my retainers no longer having ventures assigned (assumedly the venture complete window was closed, instead of being reassigned) and the program was not doing anything.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Clearly it had worked for a while, seemed to have completed 4 or 5 venture reassignments.

Sometimes when I first start the program I have to `ctrl`+`c` to get it to actually start; this does not kill the execution, it just seems to give it a kick in the pants - if it stops doing anything, I can `ctrl`+`c` then to get it going as well.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;This does not seem to be affected by the window/fullscreen/etc state of the game, whether it's minimized or active, whether the `cmd` prompt is admin or not, whether the `cmd` prompt is the active window or not, or what flags I pass the program.

I had one case where I started the program and it just immediately got stuck opening and closing a retainer's inventory - it was not able to recover given time.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Closing the window and starting program again and it worked perfectly fine.

---

Normally I would split these up, but development does seem inactive and they do seem to all fall under the same umbrella of Ventures simply not having kept up with the game; so I figured I would just go with one Issue and see where that got me.

**Comment by nvll** [comment]
Apologies, I wasn't receiving issues emails for some reason. Is this using the 0.6.0 release version, or something built from tree?

**Comment by zbee** [comment]
No worries, looks like you've done some awesome and big changes since I wrote this. It is for an earlier version. I'll go ahead and close this while I explore the new release!

**Comment by nvll** [comment]
I'm not sure the current release works in tree as it is, I may have so local changes I need to push up for it. I'll take a look this weekend.

**Comment by nvll** [comment]
Quick update: I updated ventures in the 'ventures_wip' branch for 6.1. It will look a lot different than you remember, but I just tested it locally.
