### ISSUE TITLE
Honor the NQ/HQ selection for task materials when 'use any quality' is unchecked

### ISSUE THREAD

**Issue by nvll** [nvll/xivtools#8]

**Comment by nvll** [comment]
NQ quality mats work if the box is unchecked. HQ boxes are disabled in dev to make it clear we're not handling material select right now (either 'use everything' or 'use all nq').

I'm debating the priority of this because of how rare it may be for a crafter to actually say "I want to use X hq items per craft" due to recipes after Stormblood being far easier than before, and it being micromanagement most users don't care about. Most folks have macros that are 100% with NQ mats.

**Comment by Onibus** [comment]
I came across this issue while working on some crafts. There's some merit to using a specific number of HQ items when leveling crafts. At 70, using HQ Onishi gear and crafting main/off-hand, you can very easily 100% HQ items if you have one or two HQ components.

In craft.rs, during function `select_materials`, Talan increments HQ items then proceeds to increment NQ. Instead, it might be better to increment NQ items, then increment HQ items up to count specified so when you run out of HQ materials, it won't cause synthesis to error out. This would also play in to queuing up multiple tasks and saying for the final item (such as crafting a weapon) to use at least `n` units of HQ material, assuming tasks before then were not successfully HQ'd.

**Comment by nvll** [comment]
Well, no, the "automatically select materials" option is always going to work the way it does (HQ, then NQ)  because it covers most crafts and has no chance of a user making a mistake. I don't think the way things work now needs to inform how the "specify HQ materials" option will need to work, if that's what you're saying.

The question at hand is how much I want to prioritize allowing a user to specify the specific HQ materials. It has always been in the plan, but it's lower priority than some other things.

**Comment by nvll** [comment]
e94e0c59701fe15c3f2a9feaba09ccbc56fa7df0 in dev implements this.

**Comment by nvll** [comment]
Merged into master.
